[package]
name = "dragon-core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
libc = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
half = "2"
rand = "0.8"

[features]
default = []
blas = []
